export const ADD_TODO: ADD_TODO = "ADD_TODO";
export const ADD_TODO_ERROR: ADD_TODO_ERROR = "ADD_TODO_ERROR";
export const ADD_TODO_SUCCES: ADD_TODO_SUCCES = "ADD_TODO_SUCCES";
export const ADD_TODO_PANDING: ADD_TODO_PANDING = "ADD_TODO_PANDING";

export const GET_TODOS: GET_TODOS = "GET_TODOS";
export const GET_TODOS_ERROR: GET_TODOS_ERROR = "GET_TODOS_ERROR";
export const GET_TODOS_SUCCES: GET_TODOS_SUCCES = "GET_TODOS_SUCCES";
export const GET_TODOS_PANDING: GET_TODOS_PANDING = "GET_TODOS_PANDING";

export const UPDATE_TODO: UPDATE_TODO = "UPDATE_TODO";
export const UPDATE_TODO_ERROR: UPDATE_TODO_ERROR = "UPDATE_TODO_ERROR";
export const UPDATE_TODO_SUCCES: UPDATE_TODO_SUCCES = "UPDATE_TODO_SUCCES";
export const UPDATE_TODO_PANDING: UPDATE_TODO_PANDING = "UPDATE_TODO_PANDING";

export const DELETE_TODO: DELETE_TODO = "DELETE_TODO";
export const DELETE_TODO_ERROR: DELETE_TODO_ERROR = "DELETE_TODO_ERROR";
export const DELETE_TODO_SUCCES: DELETE_TODO_SUCCES = "DELETE_TODO_SUCCES";
export const DELETE_TODO_PANDING: DELETE_TODO_PANDING = "DELETE_TODO_PANDING";

export const DELETE_ALL_TODOS: DELETE_ALL_TODOS = "DELETE_ALL_TODOS";
export const DELETE_ALL_TODOS_ERROR: DELETE_ALL_TODOS_ERROR =
  "DELETE_ALL_TODOS_ERROR";
export const DELETE_ALL_TODOS_SUCCES: DELETE_ALL_TODOS_SUCCES =
  "DELETE_ALL_TODOS_SUCCES";
export const DELETE_ALL_TODOS_PANDING: DELETE_ALL_TODOS_PANDING =
  "DELETE_ALL_TODOS_PANDING";
